import { slugify, calculateReadingTime } from "./utils";

const TOPICS: Record<string, string[]> = {
  "displays-acrilico": ["display de acrílico para balcão", "expositor acrílico personalizado", "display acrílico para produtos", "porta-folheto em acrílico"],
  supermercados: ["comunicação visual para supermercados", "displays para gôndola", "sinalização interna supermercado", "material PDV supermercado"],
  farmacias: ["comunicação visual para farmácias", "display para farmácia", "sinalização drogaria", "expositor medicamentos"],
  luminosos: ["luminoso para fachada", "letreiro luminoso LED", "caixa de luz para loja", "painel luminoso"],
  fachadas: ["fachada comercial personalizada", "fachada ACM loja", "projeto fachada comercial", "fachada supermercado"],
  "letras-caixa": ["letras caixa acrílico", "letras caixa LED", "letras caixa fachada", "letras caixa iluminadas"],
};

function generateSections(keyword: string, category: string) {
  return [
    { heading: `O que é ${keyword}?`, content: `${keyword} é essencial em comunicação visual para empresas que buscam destacar produtos no PDV. Na Mais Acrílicos, desenvolvemos projetos personalizados em ${category}.` },
    { heading: "Benefícios", content: `Investir em ${keyword} traz maior visibilidade, organização do espaço e reforço da marca. Utilizamos acrílico premium com acabamento profissional.` },
    { heading: "Como podemos ajudar", content: `A Mais Acrílicos oferece consultoria, projeto 3D, produção própria e instalação. Solicite orçamento sem compromisso.` },
  ];
}

export function generateArticleFromKeyword(keyword: string, category: string) {
  const title = `${keyword.charAt(0).toUpperCase() + keyword.slice(1)}: Guia Completo 2026`;
  const intro = `Guia completo sobre ${keyword}. A equipe Mais Acrílicos reúne tudo para você tomar a melhor decisão em comunicação visual.`;
  const sections = generateSections(keyword, category);
  const conclusion = `A Mais Acrílicos é referência em ${category}. Solicite orçamento personalizado de ${keyword}.`;
  return { title, keywords: `${keyword}, comunicação visual, PDV, Mais Acrílicos`, category, intro, sections, conclusion };
}

export function articleToHtml(t: ReturnType<typeof generateArticleFromKeyword>) {
  const body = t.sections.map((s) => `<h2>${s.heading}</h2><p>${s.content}</p>`).join("");
  return `<p>${t.intro}</p>${body}<h2>Conclusão</h2><p>${t.conclusion}</p>`;
}

export function generateSeoQueue(count = 200) {
  const queue: { title: string; keywords: string; category: string }[] = [];
  const cats = Object.keys(TOPICS);
  for (let i = 0; i < count; i++) {
    const cat = cats[i % cats.length];
    const kw = TOPICS[cat][i % TOPICS[cat].length];
    const vars = [kw, `${kw} preço`, `${kw} sob medida`, `fabricante ${kw}`, `${kw} personalizado`];
    const article = generateArticleFromKeyword(vars[i % vars.length], cat);
    queue.push({ title: article.title, keywords: article.keywords, category: cat });
  }
  return queue;
}

export function templateToPostData(t: ReturnType<typeof generateArticleFromKeyword>) {
  const content = articleToHtml(t);
  return {
    title: t.title,
    slug: slugify(t.title),
    excerpt: t.intro.slice(0, 200) + "…",
    content,
    metaTitle: t.title,
    metaDescription: t.intro.slice(0, 155) + "…",
    keywords: t.keywords,
    readingTime: calculateReadingTime(content),
    autoGenerated: true,
  };
}
